# wordings.py
# ゲーム内のすべてのテキストを一括管理するファイル

class Text:
    class UI:
        NEW_GAME = "New Game"
        CONTINUE = "Continue"
        YES = "はい"
        NO = "いいえ"
        USE_EQUIP = "使う・装備"
        DISCARD = "捨てる"
        UNEQUIP = "外す"
        WAVE = "振る"
        INVENTORY_TITLE = "アイテム"
        STAVE_TITLE = "杖"
        EQUIP_TITLE = "装備"
        EVENT_ITEM_TITLE = "貴重品"
        SHOP_TITLE = "ショップ"
        BANK_TITLE = "銀行"
        WAREHOUSE_TITLE = "預かり屋"
        GUILD_TITLE = "冒険者ギルド"
        ENHANCE_TITLE = "鍛冶屋"
        USE_WHICH_ORE = "使用する鉱石を選択してください"
        WHICH_PARAM_TO_ENHANCE = "強化するパラメータを選択してください"
        NO_ORE = "鉱石を持っていません"
        WHICH_STAVE_RECHARGE = "修復する杖を選択してください"
        NO_STAVE = "杖を持っていません"
        WHICH_TO_ENHANCE = "どれを鍛える？"
        QUEST_LIST_EMPTY = "現在受注している依頼はありません"
        ENHANCE_ARMOR_LABEL = "鎧:{name}"
        ENHANCE_SHIELD_LABEL = "盾:{name}"
        ENHANCE_WEAPON_LABEL = "{name}"
        EQUIPPED_MARK = "E:"
        SHOP_CANCEL = "-- もどる --"
        SHOP_TITLE_BUY = "購入"
        SHOP_TITLE_SELL = "売却"
        SHOP_TITLE_FULL = "--- {name} ({mode}) ---"
        SHOP_EMPTY = "商品（または所持品）がありません"
        SHOP_LOCKED_RANK = " [要ランク{rank}]"
        WAREHOUSE_CANCEL = "-- もどる --"
        WAREHOUSE_MODE_DEPOSIT = "預けるアイテムを選んでください"
        WAREHOUSE_MODE_WITHDRAW = "引き出すアイテムを選んでください"
        WAREHOUSE_EMPTY = "対象のアイテムがありません"
        BANK_TITLE_LABEL = "--- 銀行 ---"
        WAREHOUSE_CAPACITY = "保管数: {current}/{max}"
        WAREHOUSE_FEE_PANEL = "手数料: {fee} G / 所持金: {coin} G"
        WAREHOUSE_DEPOSIT = "預ける"
        WAREHOUSE_WITHDRAW = "引き出す"
        BANK_INFO = "所持金: {coin} G  /  銀行残高: {bank} G"
        BANK_DEPOSIT_100 = "100 G 預ける"
        BANK_DEPOSIT_1000 = "1000 G 預ける"
        BANK_DEPOSIT_ALL = "全額預ける"
        BANK_WITHDRAW_100 = "100 G 引き出す"
        BANK_WITHDRAW_1000 = "1000 G 引き出す"
        BANK_WITHDRAW_ALL = "全額引き出す"
        QUIT = "--もどる--"
        GOLD_LABEL = "Gold: {coin} G"
        STATUS_TIPS = "装備の性能はステータスに反映されます"
        RANK_LABEL = "Rank: {rank}"
        HOLLOW_LABEL = "Hollow"
        ATK_LABEL = "攻撃:{atk:.1f}"
        DEF_LABEL = "防御:{defense:.1f}"
        EVA_LABEL = "回避:{eva}%"
        VILLAGE = "ダンジョンの街"
        FLOOR = "B{level}F"
        MENU_TITLE = "--- MENU ---"
        QUIT_CONFIRM_MSG = "セーブせずにタイトルへ戻りますか？\nギルドか宿屋でセーブをお勧めします"
        MENU_ITEMS = "1. アイテム"
        MENU_EQUIP = "2. 装備"
        MENU_STAVES = "3. 杖"
        MENU_EVENT_ITEMS = "4. 貴重品"
        MENU_STATUS = "5. ステータス表示"
        MENU_QUESTS = "6. クエスト進捗"
        MENU_QUIT = "7. ゲームを終了する"
        MENU_MAP_TOGGLE = "8. ミニマップ表示切替"
        MENU_BACK = "--もどる--"
        STATUS_MENU_TITLE = "--- ステータスメニュー ---"
        STATUS_VIEW = "1. ステータスを表示"
        QUEST_VIEW = "2. クエスト進捗を表示"
        STATUS_HEADER = "--- PLAYER STATUS ---"
        ACTIVE_QUESTS_HEADER = "--- ACTIVE QUESTS ({current}/1) ---"
        NO_ACTIVE_QUESTS = "現在受注している依頼はありません"
        GUILD_QUEST_LIST_HEADER = "--- 冒険者ギルド ---"
        GUILD_MASTER_NEXT_RANK = "「あなたのGPは現在 {gp} です次のランクまであと {needed} GPですね」"
        GUILD_MASTER_RANK_UP_READY = "「お疲れ様でした\nGPが溜まりましたので、ランクアップの試験が受けられます\n『昇格試験』から受注できますお気をつけくださいね」"
        GUILD_MASTER_MAX_RANK = "「最高のSSランクに到達しました\nよく頑張りましたねあなたの冒険はまだまだ続きますお気をつけて」"
        NO_AVAILABLE_QUESTS = "申し訳ございません\n現在受けられる依頼はありません\nまた後で来てください"
        QUEST_ENTRY = "[{status}] {title} {progress}"
        QUEST_STATUS_REPORT = "報告"
        QUEST_STATUS_ACCEPT = "受注"
        CONFIRM_DUNGEON_START = "ダンジョンへ向かいますか？"
        CONFIRM_GO_DEEPER = "さらに奥へ進みますか？"
        CONFIRM_RETURN_VILLAGE = "村に戻りますか？"
        CONFIRM_GO_UPPER = "上の階層に戻りますか？"
        RANK_LIMIT_REACHED = "この先へ進むには ギルドランク {rank} 以上が必要だ"
        STATUS_TIPS = "正面から攻撃を受ける際、盾を装備していると\n自動的にガードが発生し、ダメージを回避できます\n背後や側面からの攻撃には注意しましょう"
        INN_CONFIRM = "一泊 {fee} G だよ泊まっていくかい？"
        DOCTOR_POISON_CONFIRM = "ひどい毒に侵されているな\n{fee} Gで解毒と治療をしてやろうか？"
        DOCTOR_HEAL_CONFIRM = "傷ついているようだな\n{fee} Gで治療してやろうか？"
        DOCTOR_HEALTHY = "どこも悪くないようだな\n健康なのは良いことだね"
        SHOP_BUY_CONFIRM = "{name} を {price} G で買いますか？"
        SHOP_SELL_CONFIRM = "{name} を {price} G で売りますか？"
        GUILD_ABANDON_CONFIRM = "キャンセルするとお金が {penalty} G\nGPが {gp_penalty} 減りますよろしいですか？"
        GUILD_ABANDON_DONE = "違約金 {penalty} G を支払い、{gp_penalty} GP を失った"
        GUILD_ABANDON_NO_COIN = "違約金 {penalty} G が足りないぞ"
        GUILD_QUEST_UNMET = "条件を満たしていないようです"
        GUILD_RANK_UP_NOTICE = "\n「おめでとう {rank}級のテストが受けられるようになりましたよ」"
        GUILD_NO_ENTRY = "ギルドに所属していない者は ダンジョンに入れません\nまずはギルドで『入会試験』を受けてください"
        GUILD_LIST_EMPTY = "受けられる依頼なし"
        STATUS_MENU_HINT = "カテゴリを選択してください"
        GUILD_REPORT_CONGRATS = "クエスト達成"
        GUILD_REPORT_REWARD = "報酬: {gold} G / {gp} GP"
        GUILD_REPORT_RANK_UP = "報酬: ギルドランク {rank} への昇格"
        GUILD_REPORT_GUIDE = "--- [決定キー] を押して報酬を受け取る ---"
        GUILD_REPORT_CONFIRM = "{name} をすでにお持ちですね 納品しますか？"
        GUILD_REPORT_CONFIRM_GENERIC = "クエストを報告しますか？"
        NOW_LOADING = "Now Loading..."
        SAVING = "Saving..."
        STAT_ARMOR_PENETRATION = "[貫]防御無視"
        STAT_ARMOR_PENETRATION_LABEL = "防御無視"
        STAT_CONFUSION_ICON = "[乱]困惑"
        STAT_CONFUSION_LABEL = "困惑"

    class System:
        GAME_OVER = "死んでしまった\n所持金が半分になり、死の呪いが進行した"
        DOCTOR_REVIVE = "大手術だったよ（治療費: {penalty} G）\n命があっただけでも儲け物だよ \nお気をつけて"
        STAIRS_CONFIRM = "次の階層へ進みますか？"
        OVERFLOW_SENSE = "モンスター氾濫の 予感がする……"
        OVERFLOW_START = "モンスター氾濫が 発生した"
        OVERFLOW_SURVIVE = "大量のモンスターを前に、生き残れるか"
        OUTBREAK_BLOCKED = "魔物の氾濫（アウトブレイク）が発生している！\n安全が確保されるまで、元来た階段は使用できない！"

    class Combat:
        BLOCK = "{target} は 盾で 攻撃を ブロックした"
        DAMAGE = "{attacker} は {target} に {damage} ダメージを与えた"
        CRITICAL = "クリティカルヒット "
        MISS = "{attacker} の 攻撃は 外れた"
        CONFUSED = "{target} は困惑し、意識が乱れている！（+{amount}）"

    class Items:
        GET = "{name} を 手に入れた！"
        USE_NOTHING = "{item} を 使った\nしかし 何も 起こらなかった"
        RECOVER_HP = "{item} を 使った\nHPが {recovered} 回復した"
        ANTIDOTE_USE = "{name}を使用した 毒が消えた"
        POISON_SELF_USE = "{name}を使用した！ ウッ、身体が毒に侵された！"
        WARP_HOME_USE = "{name}を使用した 身体が光に包まれる..."
        BUFF_ATTACK_USE = "{name}を使用した！ 攻撃力が一時的に上昇し、防御無視と会心率が強化された！"
        BUFF_REGEN_USE = "{name}を使用した！ 自然回復が一時的に上昇し、回復アイテムの効果がアップした！"
        BUFF_MAGIC_USE = "{name}を使用した！ 魔法が一時的に強化され、すべての杖の回数が{stave_recovery}回復した！"
        BUFF_STEALTH_USE = "{name}を使用した！ 視界が広がり、敵に気づかれにくくなった！"
        BUFF_OVERWRITE_CONFIRM = "秘薬の効果が残っています\n{name}を飲むと現在の効果は消えます\nよろしいですか？"
        MATERIAL_DESC = "それは素材だ鍛冶屋に持っていこう"
        GET_LANTERN = "{name} を 手に入れた！\nインベントリの装備から 切り替えられます"
        EQUIPPED_CANT_DISCARD = "装備中なので捨てられません"
        DISCARDED = "{name} を 捨てた"
        EQUIPPED = "{name} を 装備した"
        HELD = "{name} を 持った"
        STAVE_NO_POWER = "その杖は もう 力が残っていない"
        STAVE_NOT_FOUND = "杖が見つかりません"
        WARP_HOME_QUEST_READY = "依頼の条件を達成している時は\n自力で村まで帰らなくてはならない！"
        NO_STAVES = "杖を 持っていない"
        RECHARGED = "{name} の 回数が {amount} 回復した\n(現在: {charges}回)"
        ENHANCED = "鍛冶屋「おっしゃ、できたぜ！ {name} に鍛え直してやったぜ」"
        UNEQUIPPED = "{name} を 外した"
        BAG_FULL = "バッグがいっぱいだよ"
        BAG_FULL_SHOP = "バッグがいっぱいだね\n何か整理してきなよ"
        NOT_ENOUGH_COIN = "お金が足りないよ"
        BOUGHT = "{name} を 買ったよ"
        SOLD = "{name} を {price} コインで売ったよ"
        CANT_SELL_EQUIPPED = "装備中のものは売れないよ"
        ITEM_NOT_FOUND = "アイテムが見つかりませんでした"
        RANK_REQUIRED = "この商品を買うにはギルドランク {rank} 以上が必要です"

    class NPC:
        INN_WELCOME = "今日もご苦労様 ゆっくり休んでいくかい？"
        INN_FEE_INFO = "宿泊代は {fee} G だよお金が足りないみたいだね"
        INN_RECOVERED = "今日もご苦労様でした \nこれまでの冒険を 確実に 記録しましたよ"
        INN_DEBT = "お金が足りないだって しょうがない、今回はツケにしておいてあげるよ"
        INN_NO = "無理するんじゃないよー"
        WEAPON_SHOP_WELCOME = "いらっしゃい 武器と防具のことならお任せな"
        DEDICATED_WEAPON_SHOP_WELCOME = "いらっしゃい！うちは武器専門店だぜ"
        DEDICATED_ARMOR_SHOP_WELCOME = "いらっしゃい！うちは防具と盾の専門店だ"
        DEDICATED_ACCESSORY_SHOP_WELCOME = "いらっしゃいませ。こちらは装飾品（アクセサリ）専門店です"
        ITEM_SHOP_WELCOME = "いらっしゃいませ薬や巻物など、冒険の必需品を取り揃えております"
        MERCHANT_WELCOME = "へっへっへ、いいモノあるよ買っていくかい？"
        BANK_WELCOME = "預金なら当銀行へ お預け入れですか？お引き出しですか？"
        WAREHOUSE_WELCOME = "荷物が重くなったら預かり所へ なにかお預かりしますか？"
        BLACKSMITH_WELCOME = "鉱石を持ってくれば装備を叩き直してやるぜ\n装備には成長の限界がある\n最初は効果が大きいが、鍛えすぎると変化が極小さくなるぞ\nMax Limitと出たらもう鍛えられないぜ"
        BLACKSMITH_NO_ORE = "武器や防具を鍛えたいなら『鉱石』を持ってきな"
        BLACKSMITH_NO_ITEM = "おいおい、その鉱石は持ってないじゃないか"
        BLACKSMITH_ENHANCE_PREVIEW = "{name}\n{label}: {before:.2f}{unit} → {after:.2f}{unit}\n強化回数: +{enhance}回目 (+{ore_bonus})"
        GUILD_LIMIT = "これ以上は同時に依頼を受けられません"
        GUILD_ACCEPTED = "{title}』を受注した\n頑張ってこいよ"
        GUILD_COMPLETED = "依頼達成です\n報酬として {gold} G と {gp} GP を受け取った"
        GUILD_RANK_UP_DONE = "がんばりましたね これでランク{rank}に昇格ですおめでとう"
        GUILD_WELCOME_UNRANKED = "ようこそ冒険者ギルドへ\nまずは冒険者になるための実力を示してください\n「昇給試験を受ける」から試験を受けてください"
        GUILD_REMIND_UNRANKED = "入会試験の内容は覚えていますか？\n地下5階にある『冒険者の証』を持ち帰ってきてください"
        GUILD_WELCOME_RANKUP_READY = "お疲れ様でした\nGPが貯まりましたので、\n新しいランクへの『昇級試験』を受けることができます"
        GUILD_WELCOME_DEFAULT = "ようこそ今日はどんな用件ですか"
        GUILD_ACCEPT_CONFIRM = "「{title}」の依頼ですね\nよろしいですか"
        GUILD_ACCEPT_DONE = "「よろしくお願いします頑張ってきてくださいね」"
        GUILD_HUNT_PROGRESS = "討伐頑張ってください\n(現在: {current}/{total})"
        GUILD_DELIVERY_PROGRESS = "納品頑張ってください\n(現在: {current}/{total})"
        DOCTOR_OK = "もう大丈夫だよお大事に\n"
        BANK_DEPOSITED = "{amount} G 預かりました"
        BANK_WITHDRAWN = "{amount} G 引き出しました"
        BANK_NO_MONEY = "そんなに持っていないよ"
        BANK_NO_DEPOSIT = "預けるお金がないよ"
        BANK_NO_WITHDRAW = "銀行にそんなに預けていないよ"
        BANK_NO_BANK_MONEY = "引き出すお金がないよ"
        WAREHOUSE_FULL = "預かり所がいっぱいだよ"
        WAREHOUSE_NO_FEE = "手数料 {fee} G が足りないよ"
        WAREHOUSE_CONFIRM_DEPOSIT = "手数料 {fee} G で {name} を預けますか？"
        WAREHOUSE_CONFIRM_WITHDRAW = "手数料 {fee} G で {name} を引き出しますか？"
        GENERIC_FALLBACK = "私は {name} です"
        PRIEST_WELCOME = "ようこそ …おや、あなたには死の呪いがかかっているようですね"
        PRIEST_HEALTHY = "あなたは呪われていません \n神の加護があらんことを"
        PRIEST_NO_GP = "ギルドポイント(GP)が足りないようです \n呪いの解除には {cost} GP必要です"
        PRIEST_CURE_CONFIRM = "ギルドポイント(GP)を {cost} GP 捧げることで、死の呪いを1段階解除できます\n儀式を行いますか？"
        PRIEST_CURE_DONE = "死の呪いが一段階解除されました！\n【{stat}】の低下ペナルティが消失しました"
        PRIEST_CURE_DONE_SIMPLE = "死の呪いが一段階解除されました！"
        PRIEST_DECLINE = "神の加護があらんことを"

    class Guild:
        QUEST_HUNT_TITLE = "[{rank}] {name}を{amount}匹討伐"
        QUEST_DESTROY_TITLE = "[{rank}] {name}を{amount}個破壊"
        QUEST_DELIVERY_TITLE = "[{rank}] {name}を{amount}個納品"
        QUEST_RANK_UP_TITLE = "{rank}ランクへの昇格"
        
        # フレーバーテキスト用テンプレート
        QUEST_HUNT_FLAVORS = [
            "最近、ダンジョンの浅層で{name}が増えすぎて困っています 少し数を減らしてください",
            "探索中の商人が{name}に襲われました 安全確保のため討伐をお願いします",
            "生態系の調査のため、特定の階層における{name}の個体数調整が必要です",
            "深層へ向かうルートに{name}が群生しています 早急な対応を！",
            "探索のついでに、{name}を片付けてきてくれませんか？"
        ]
        QUEST_DESTROY_FLAVORS = [
            "探索路に{name}が放置されていて邪魔です 撤去をお願いします",
            "古びた{name}が通路を塞いでいます 破壊して進路を確保してください",
            "放置された{name}が探索の妨げになっています 片付けてください",
            "{name}の中に魔物が潜んでいるとの報告がありました 今のうちに破壊を！",
            "探索路の整備のため、邪魔な{name}の撤去を依頼します"
        ]
        QUEST_DELIVERY_FLAVORS = [
            "魔法の研究のために{name}が必要です 分けていただけませんか？",
            "娘の誕生日に{name}を贈りたいのですが、自分では手に入らなくて…",
            "お客さんから{name}の注文が入りました 至急納品をお願いします！",
            "備蓄用の{name}が底を突いてしまいました 協力をお願いします",
            "珍しい{name}に興味があります 見つけたら持ってきてください"
        ]
        QUEST_REQUESTER_NPCS = [
            "ギルドマスター", "ギルドの受付嬢", "鍛冶屋の親方", "道具屋の店主", 
            "武器屋の親父", "宿屋の女将", "銀行員", "預かり所の管理人",
            "村の医者", "大魔導士", "見習い冒険者", "宿屋の看板娘",
            "倉庫の管理人"
        ]
        QUEST_REQUESTER_OTHERS = [
            "迷子の少女", "村の老人", "引退した冒険者", "怪しい研究者", 
            "心配性の母親", "腕利きの料理人", "商人のギルド長", "新米の衛兵",
            "お忍びの貴族", "近所の農夫", "旅の僧侶", "名もなき旅人",
            "困り果てた開拓者", "異国の商人"
        ]

    class Trap:
        TRIGGERED = "{name} を踏んだ\n"
        PITFALL = "真っ暗な穴に 落ちていく..."
        DAMAGE_FLOOR = "{damage} ダメージを受けた"
        MINE = "地雷を踏んだ {damage} ダメージ"
